import {openLibraryPlay} from './helpers/play-library.js';
import {test,expect,request as requests} from '@playwright/test';
import {newBoard,clone,fromSituation} from '../src/lib/plays/board.js';
test.use({hasTouch:true});
async function login(request,baseURL){await request.post('/api/auth/login',{headers:{Origin:new URL(baseURL).origin},data:{role:'admin',password:'password'}});}
async function saveBoard(request,board){const response=await request.post('/api/boards',{data:{board}});expect(response.status()).toBe(201);return {...await response.json(),board};}
async function exampleSituation(request,prefix){const source=(await (await request.get('/api/situations')).json())[0];const b=fromSituation(source);const input={...source,key:`lib-${crypto.randomUUID()}`,title:`${prefix} situation`,revision:undefined,displayCode:undefined,ballLocation:'RF',primaryCategory:'cutoffs-relays',relatedCategories:['backups-rotations'],desc:'Library searchable coaching description',boardAnimation:{version:2,movements:b.movements,battedBall:b.battedBall}};delete input.variationNumber;delete input.variationTagVersion;const response=await request.post('/api/situations',{data:input});expect(response.status()).toBe(201);return (await response.json()).record;}
async function browse(page){await page.getByRole('button',{name:'Browse Library',exact:true}).click();return page.getByRole('dialog');}

test('server search, independent/combined filters, deterministic pagination and literal queries',async({request,baseURL})=>{
 await login(request,baseURL);const prefix=`Filter ${Date.now()}`;const values=[];
 for(let i=0;i<3;i++){const b=newBoard();b.title=`${prefix} ${['Zulu','Alpha','Middle'][i]}`;b.outs=i;b.runners=i?{first:{x:2170,y:1304}}:{};b.battedBall={type:['ground_ball','line_drive','fly_ball'][i],start:{x:1577,y:1734},destination:{x:2000,y:800}};values.push(await saveBoard(request,b));}
 const situation=await exampleSituation(request,prefix);
 const list=async params=>(await (await request.get(`/api/play-library?${new URLSearchParams(params)}`)).json());
 expect((await list({q:prefix})).total).toBe(4);expect((await list({q:prefix,type:'board'})).total).toBe(3);expect((await list({q:prefix,type:'situation'})).total).toBe(1);
 for(let i=0;i<3;i++){expect((await list({q:prefix,type:'board',outs:String(i)})).items.map(x=>x.id)).toEqual([values[i].id]);expect((await list({q:prefix,type:'board',ball:['ground_ball','line_drive','air_ball'][i]})).items.map(x=>x.id)).toEqual([values[i].id]);}
 expect((await list({q:prefix,type:'board',runners:'0'})).total).toBe(1);expect((await list({q:prefix,type:'board',runners:'1',outs:'1',ball:'line_drive'})).items.map(x=>x.id)).toEqual([values[1].id]);
 expect((await list({q:prefix,location:'RF'})).items.map(x=>x.id)).toEqual([situation.key]);expect((await list({q:prefix,concept:'cutoffs-relays'})).total).toBe(1);expect((await list({q:prefix,concept:'backups-rotations'})).total).toBe(1);expect((await list({q:'searchable coaching description'})).items.some(x=>x.id===situation.key)).toBe(true);
 const page=await list({q:prefix,type:'board',sort:'title',limit:'2'});expect(page.items.map(x=>x.title)).toEqual([`${prefix} Alpha`,`${prefix} Middle`]);expect((await list({q:prefix,type:'board',sort:'title',limit:'2',offset:'2'})).items.map(x=>x.title)).toEqual([`${prefix} Zulu`]);
 for(const sort of ['updated','created']){const result=await list({q:prefix,sort});const times=result.items.map(x=>Date.parse(((sort==='updated'?x.updatedAt:x.createdAt).replace(' ','T')).replace(/(?<!Z)$/,'Z')));expect(times).toEqual([...times].sort((a,b)=>b-a));}
 expect((await list({q:'%_never_match'})).total).toBe(0);expect((await request.get('/api/play-library?sort=unsafe')).status()).toBe(400);expect((await request.get('/api/play-library?offset=-1')).status()).toBe(400);
});

test('library duplicates a Board, saves independent paths, presents, and safely deletes',async({page,baseURL})=>{
 await login(page.request,baseURL);const original=newBoard();original.title=`Copy board ${Date.now()}`;original.movements.SS=[{path:[clone(original.defenders.SS),{x:1400,y:850}],start:{event:'contact'}}];const saved=await saveBoard(page.request,original);
 await page.goto('/coach-board?edit=1');let library=await browse(page);await library.getByLabel('Search plays').fill(original.title);const row=library.getByRole('article',{name:`Board: ${original.title}`,exact:true});await row.getByRole('button',{name:'Duplicate',exact:true}).click();await row.getByLabel('Copy name').fill(`${original.title} changed`);await row.getByRole('button',{name:'Open Copy'}).click();await expect(library).toHaveCount(0);await page.getByRole('button',{name:'Save Board',exact:true}).click();await expect(page.getByRole('status')).toHaveText('Board saved.');
 const records=await (await page.request.get('/api/boards')).json(),copy=records.find(x=>x.board.title.endsWith('changed'));expect(copy.id).not.toBe(saved.id);expect(copy.board.movements).toEqual(original.movements);expect(records.find(x=>x.id===saved.id).board).toEqual(original);
 library=await browse(page);await library.getByLabel('Search plays').fill(copy.board.title);await library.getByRole('article',{name:`Board: ${copy.board.title}`,exact:true}).getByRole('button',{name:`Present ${copy.board.title}`,exact:true}).click();await expect(page.getByRole('region',{name:'Presentation controls'})).toBeVisible();await page.getByRole('button',{name:'Back to Library'}).click();await openLibraryPlay(page,'board',copy.id,copy.board.title);
 page.once('dialog',d=>d.dismiss());await page.getByRole('button',{name:'Delete Board',exact:true}).click();expect((await page.request.get(`/api/play-library/board/${copy.id}`)).status()).toBe(200);page.once('dialog',d=>d.accept());await page.getByRole('button',{name:'Delete Board',exact:true}).click();await expect(page.getByRole('status')).toContainText('Saved Board deleted');expect((await page.request.get(`/api/play-library/board/${saved.id}`)).status()).toBe(200);expect((await page.request.get(`/api/play-library/board/${copy.id}`)).status()).toBe(404);
});

test('Situation copy retains animation, publishes a new identity and archives from its tools',async({page,baseURL})=>{
 await login(page.request,baseURL);const original=await exampleSituation(page.request,`Situation copy ${Date.now()}`);await page.goto('/coach-board?edit=1');let library=await browse(page);await library.getByLabel('Search plays').fill(original.title);let row=library.getByRole('article',{name:`Situation: ${original.title}`,exact:true});await row.getByRole('button',{name:'Duplicate',exact:true}).click();const title=`${original.title} new`;await row.getByLabel('Copy name').fill(title);await row.getByRole('button',{name:'Open Copy'}).click();await page.getByRole('button',{name:'Save Situation Changes',exact:true}).click();await page.getByRole('button',{name:'Publish Situation',exact:true}).click();await expect(page.getByRole('status')).toHaveText('Situation changes saved.');const copy=(await (await page.request.get('/api/situations')).json()).find(s=>s.title===title);expect(copy.key).not.toBe(original.key);expect(copy.displayCode).not.toBe(original.displayCode);expect(copy.boardAnimation).toEqual(original.boardAnimation);expect(await (await page.request.get(`/api/play-library/situation/${original.key}`)).json()).toEqual(original);
 await page.getByRole('button',{name:'Back to Board Tools'}).click();await expect(page.getByRole('button',{name:'Situation Details'})).toHaveCount(0);
 await page.goto('/coach-board?edit=1');await openLibraryPlay(page,'situation',copy.key,title);page.once('dialog',d=>d.accept());await page.getByRole('button',{name:'Archive Situation'}).click();await expect(page.getByRole('status')).toContainText('Situation archived');expect((await page.request.get(`/api/play-library/situation/${copy.key}`)).status()).toBe(404);expect((await page.request.get(`/api/play-library/situation/${original.key}`)).status()).toBe(200);
});

test('private Board results/details/delete stay owner-scoped and players cannot access library',async({request,baseURL})=>{
 expect((await request.get('/api/play-library')).status()).toBe(401);await login(request,baseURL);const b=newBoard();b.title=`Private library ${Date.now()}`;const saved=await saveBoard(request,b);const headers={Origin:new URL(baseURL).origin};
 const coach=await requests.newContext({baseURL});
 // A dedicated coach account below avoids depending on seed username conventions.
 const team=`library-owner-${Date.now()}`,id=`${team}-coach`;await request.post('/api/admin/teams',{headers,data:{id:team,name:team}});const member=await request.post(`/api/admin/teams/${team}/members`,{headers,data:{userId:id,name:'Library Coach',role:'coach',password:'Initial-1234'}});expect(member.status()).toBe(201);await coach.post('/api/auth/login',{headers,data:{role:'coach',teamId:team,coachId:id,password:'Initial-1234'}});expect((await coach.put('/api/auth/password',{headers,data:{currentPassword:'Initial-1234',newPassword:'Changed-1234'}})).ok()).toBeTruthy();
 expect((await coach.get(`/api/play-library?q=${encodeURIComponent(b.title)}`)).status()).toBe(200);expect((await (await coach.get(`/api/play-library?q=${encodeURIComponent(b.title)}`)).json()).total).toBe(0);expect((await coach.get(`/api/play-library/board/${saved.id}`)).status()).toBe(404);expect((await coach.delete(`/api/play-library/board/${saved.id}`,{headers:{...headers,'If-Match':'1'}})).status()).toBe(409);expect((await coach.delete('/api/situations/unknown',{headers:{...headers,'If-Match':'1'}})).status()).toBe(403);expect((await coach.post('/api/situations',{headers,data:{key:'copy',title:'copy'}})).status()).toBe(403);
 const player=await requests.newContext({baseURL});await player.post('/api/auth/login',{headers,data:{role:'player',teamId:'13u-black',playerId:'13u-black-bob-smith-11',password:'password'}});expect((await player.get('/api/play-library')).status()).toBe(403);expect((await player.get(`/api/play-library/board/${saved.id}`)).status()).toBe(403);
 expect((await request.delete(`/api/play-library/board/${saved.id}`,{headers:{Origin:'https://other.example','If-Match':'1'}})).status()).toBe(403);expect((await request.delete(`/api/play-library/board/${saved.id}`)).status()).toBe(428);expect((await request.delete(`/api/play-library/board/${saved.id}`,{headers:{'If-Match':'2'}})).status()).toBe(409);
 await coach.dispose();await player.dispose();
});

test('mobile and tablet library filters, empty results and actions fit the viewport',async({page,baseURL})=>{
 await login(page.request,baseURL);await page.goto('/coach-board?edit=1');for(const width of [390,820,1280]){await page.setViewportSize({width,height:900});const library=await browse(page);await library.getByLabel('Search plays').fill('no-matching-library-example-1928');await expect(library.getByRole('heading',{name:'No matching plays'})).toBeVisible();expect(await library.evaluate(el=>el.scrollWidth<=el.clientWidth)).toBe(true);await page.screenshot({path:`/tmp/library-${width}.png`,fullPage:true});await library.getByRole('button',{name:'Clear Filters'}).tap();await expect(library.getByRole('article').first()).toBeVisible();expect(await library.evaluate(el=>el.scrollWidth<=el.clientWidth)).toBe(true);await page.screenshot({path:`/tmp/library-filled-${width}.png`,fullPage:true});await library.getByRole('button',{name:'Close Library'}).tap();await expect(page.getByRole('button',{name:'Browse Library'})).toBeFocused();}
});

test('a coach without publishing access can copy a shared Situation into a review proposal',async({page,request,baseURL})=>{
 await login(request,baseURL);const original=await exampleSituation(request,`Review library ${Date.now()}`);const headers={Origin:new URL(baseURL).origin};await page.request.post('/api/auth/login',{headers,data:{role:'coach',teamId:'13u-black',coachId:'staff-coach',password:'password'}});
 await page.goto('/coach-board?edit=1');const library=await browse(page);await library.getByLabel('Search plays').fill(original.title);const row=library.getByRole('article',{name:`Situation: ${original.title}`,exact:true});await expect(row.getByRole('button',{name:'Archive Situation'})).toHaveCount(0);await row.getByRole('button',{name:'Duplicate',exact:true}).click();const title=`${original.title} coach copy`;await row.getByLabel('Copy name').fill(title);await row.getByRole('button',{name:'Open Copy'}).click();await page.getByRole('button',{name:'Save Situation Changes',exact:true}).click();await expect(page.getByRole('button',{name:'Publish Situation'})).toHaveCount(0);await page.getByLabel('Proposal reason').fill('Adapt this play for our team.');await page.getByRole('button',{name:'Submit for Review'}).click();await expect(page.getByRole('status')).toContainText('Proposal submitted');const proposal=(await (await page.request.get('/api/situation-submissions')).json()).submissions.find(s=>s.situation.title===title);expect(proposal.submissionType).toBe('create');expect(proposal.situation.key).not.toBe(original.key);expect(proposal.situation.boardAnimation).toEqual(original.boardAnimation);expect(await (await request.get(`/api/play-library/situation/${original.key}`)).json()).toEqual(original);
});

test('main Coach Board opens cards; selection presents paused, with edit, library return and creation',async({page,baseURL})=>{
 await login(page.request,baseURL);const board=newBoard();board.title=`Card entry ${Date.now()}`;board.outs=1;board.runners={first:{x:2170,y:1304}};board.movements.SS=[{path:[clone(board.defenders.SS),{x:1500,y:900}],start:{event:'contact'}}];const saved=await saveBoard(page.request,board);
 await page.goto('/');await expect(page.locator('html')).toHaveAttribute('data-diq-runtime','loaded');await page.evaluate(()=>window.__DIQ_READY__);await Promise.all([page.waitForEvent('load'),page.getByRole('button',{name:'Coach Board',exact:true}).click()]);const library=page.getByRole('dialog');await expect(library).toBeVisible();await expect(page.getByRole('complementary',{name:'Coach Board tools'})).toHaveCount(0);await library.getByLabel('Search plays').fill(board.title);await library.getByText('Baseball filters',{exact:true}).click();await library.getByRole('combobox',{name:'Outs',exact:true}).selectOption('1');await library.getByRole('combobox',{name:'Runners',exact:true}).selectOption('1');const card=library.locator(`article[data-content-id="${saved.id}"]`);await expect(card.locator('.training-base-map .is-occupied')).toHaveCount(1);await expect(card.locator('.training-out-map .is-recorded')).toHaveCount(1);await expect(card.locator('.date,.playbook-card-metadata')).toHaveCount(0);
 for(const name of ['Situation Details','Save as Situation','Delete Board','Archive Situation'])await expect(library.getByRole('button',{name,exact:true})).toHaveCount(0);
 await card.getByRole('button',{name:`Present ${board.title}`,exact:true}).click();const controls=page.getByRole('region',{name:'Presentation controls'});await expect(controls.getByRole('status')).toHaveText('Starting alignment');await expect(controls.getByRole('button',{name:'Play',exact:true})).toBeVisible();await expect(controls.getByRole('button',{name:'Pause',exact:true})).toHaveCount(0);await expect(page.getByRole('button',{name:'Edit',exact:true})).toHaveCount(0);await expect(controls.getByLabel('Show Labels')).toHaveCount(0);await page.getByRole('button',{name:'Back to Library'}).click();await openLibraryPlay(page,'board',saved.id,board.title);await expect(page.getByLabel('Board name')).toHaveValue(board.title);await expect(page.getByText('Load Board or Situation',{exact:true})).toHaveCount(0);await expect(page.getByRole('button',{name:'Delete Board',exact:true})).toBeVisible();
 await page.getByLabel('Board name').fill(`${board.title} unsaved`);await page.getByRole('button',{name:'Present',exact:true}).click();await page.getByRole('button',{name:'Back to Library'}).click();await expect(library).toBeVisible();await library.getByRole('button',{name:'Close Library'}).click();await expect(page.getByLabel('Board name')).toHaveValue(`${board.title} unsaved`);
 await page.getByRole('button',{name:'Browse Library'}).click();page.once('dialog',d=>d.dismiss());await library.getByRole('button',{name:'New Board',exact:true}).click();await expect(library).toBeVisible();page.once('dialog',d=>d.accept());await library.getByRole('button',{name:'New Board',exact:true}).click();await expect(page.getByLabel('Board name')).toHaveValue('Untitled Board');await expect(page.getByRole('region',{name:'Presentation controls'})).toHaveCount(0);
 for(const width of [390,820]){await page.setViewportSize({width,height:900});await openLibraryPlay(page,'board',saved.id,board.title,'present');await expect(page.getByRole('button',{name:'Edit',exact:true})).toHaveCount(0);expect(await page.getByRole('button',{name:'Back to Library'}).evaluate(el=>el.getBoundingClientRect().right<=innerWidth)).toBe(true);await page.getByRole('button',{name:'Back to Library'}).tap();await library.getByLabel('Search plays').fill(board.title);await page.screenshot({path:`/tmp/library-card-${width}.png`,fullPage:true});await card.getByRole('button',{name:'Edit',exact:true}).tap();await expect(page.getByLabel('Board name')).toHaveValue(board.title);}
});


test('closing library after a card presentation returns to main rather than opening editor',async({page,baseURL})=>{
 await login(page.request,baseURL);const board=newBoard();board.title=`Presentation return ${Date.now()}`;const saved=await saveBoard(page.request,board);
 await page.goto('/coach-board');const library=page.getByRole('dialog');await expect(library).toBeVisible();await library.getByLabel('Search plays').fill(board.title);await library.locator(`article[data-content-id="${saved.id}"]`).getByRole('button',{name:`Present ${board.title}`,exact:true}).click();
 await page.getByRole('button',{name:'Back to Library',exact:true}).click();await expect(library).toBeVisible();await library.getByRole('button',{name:'Close Library',exact:true}).click();await expect(page).toHaveURL(new URL('/',baseURL).href);await expect(page.locator('html')).toHaveAttribute('data-diq-runtime','loaded');await expect(page.getByRole('button',{name:'Coach Board',exact:true})).toBeVisible();
});
